package com.work.pojo;

import java.util.Date;

public class Cost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.shop
     *
     * @mbg.generated
     */
    private Double shop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.sp_message
     *
     * @mbg.generated
     */
    private String spMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.meat
     *
     * @mbg.generated
     */
    private Double meat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.mt_message
     *
     * @mbg.generated
     */
    private String mtMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.house
     *
     * @mbg.generated
     */
    private Double house;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.he_message
     *
     * @mbg.generated
     */
    private String heMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.travel
     *
     * @mbg.generated
     */
    private Double travel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.tl_message
     *
     * @mbg.generated
     */
    private String tlMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.lark
     *
     * @mbg.generated
     */
    private Double lark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.lk_message
     *
     * @mbg.generated
     */
    private String lkMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.lend
     *
     * @mbg.generated
     */
    private Double lend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.ld_message
     *
     * @mbg.generated
     */
    private String ldMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.ct_repay
     *
     * @mbg.generated
     */
    private Double ctRepay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.cry_message
     *
     * @mbg.generated
     */
    private String cryMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.ct_date
     *
     * @mbg.generated
     */
    private Date ctDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.id
     *
     * @return the value of cost.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.id
     *
     * @param id the value for cost.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.shop
     *
     * @return the value of cost.shop
     *
     * @mbg.generated
     */
    public Double getShop() {
        return shop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.shop
     *
     * @param shop the value for cost.shop
     *
     * @mbg.generated
     */
    public void setShop(Double shop) {
        this.shop = shop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.sp_message
     *
     * @return the value of cost.sp_message
     *
     * @mbg.generated
     */
    public String getSpMessage() {
        return spMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.sp_message
     *
     * @param spMessage the value for cost.sp_message
     *
     * @mbg.generated
     */
    public void setSpMessage(String spMessage) {
        this.spMessage = spMessage == null ? null : spMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.meat
     *
     * @return the value of cost.meat
     *
     * @mbg.generated
     */
    public Double getMeat() {
        return meat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.meat
     *
     * @param meat the value for cost.meat
     *
     * @mbg.generated
     */
    public void setMeat(Double meat) {
        this.meat = meat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.mt_message
     *
     * @return the value of cost.mt_message
     *
     * @mbg.generated
     */
    public String getMtMessage() {
        return mtMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.mt_message
     *
     * @param mtMessage the value for cost.mt_message
     *
     * @mbg.generated
     */
    public void setMtMessage(String mtMessage) {
        this.mtMessage = mtMessage == null ? null : mtMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.house
     *
     * @return the value of cost.house
     *
     * @mbg.generated
     */
    public Double getHouse() {
        return house;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.house
     *
     * @param house the value for cost.house
     *
     * @mbg.generated
     */
    public void setHouse(Double house) {
        this.house = house;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.he_message
     *
     * @return the value of cost.he_message
     *
     * @mbg.generated
     */
    public String getHeMessage() {
        return heMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.he_message
     *
     * @param heMessage the value for cost.he_message
     *
     * @mbg.generated
     */
    public void setHeMessage(String heMessage) {
        this.heMessage = heMessage == null ? null : heMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.travel
     *
     * @return the value of cost.travel
     *
     * @mbg.generated
     */
    public Double getTravel() {
        return travel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.travel
     *
     * @param travel the value for cost.travel
     *
     * @mbg.generated
     */
    public void setTravel(Double travel) {
        this.travel = travel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.tl_message
     *
     * @return the value of cost.tl_message
     *
     * @mbg.generated
     */
    public String getTlMessage() {
        return tlMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.tl_message
     *
     * @param tlMessage the value for cost.tl_message
     *
     * @mbg.generated
     */
    public void setTlMessage(String tlMessage) {
        this.tlMessage = tlMessage == null ? null : tlMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.lark
     *
     * @return the value of cost.lark
     *
     * @mbg.generated
     */
    public Double getLark() {
        return lark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.lark
     *
     * @param lark the value for cost.lark
     *
     * @mbg.generated
     */
    public void setLark(Double lark) {
        this.lark = lark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.lk_message
     *
     * @return the value of cost.lk_message
     *
     * @mbg.generated
     */
    public String getLkMessage() {
        return lkMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.lk_message
     *
     * @param lkMessage the value for cost.lk_message
     *
     * @mbg.generated
     */
    public void setLkMessage(String lkMessage) {
        this.lkMessage = lkMessage == null ? null : lkMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.lend
     *
     * @return the value of cost.lend
     *
     * @mbg.generated
     */
    public Double getLend() {
        return lend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.lend
     *
     * @param lend the value for cost.lend
     *
     * @mbg.generated
     */
    public void setLend(Double lend) {
        this.lend = lend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.ld_message
     *
     * @return the value of cost.ld_message
     *
     * @mbg.generated
     */
    public String getLdMessage() {
        return ldMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.ld_message
     *
     * @param ldMessage the value for cost.ld_message
     *
     * @mbg.generated
     */
    public void setLdMessage(String ldMessage) {
        this.ldMessage = ldMessage == null ? null : ldMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.ct_repay
     *
     * @return the value of cost.ct_repay
     *
     * @mbg.generated
     */
    public Double getCtRepay() {
        return ctRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.ct_repay
     *
     * @param ctRepay the value for cost.ct_repay
     *
     * @mbg.generated
     */
    public void setCtRepay(Double ctRepay) {
        this.ctRepay = ctRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.cry_message
     *
     * @return the value of cost.cry_message
     *
     * @mbg.generated
     */
    public String getCryMessage() {
        return cryMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.cry_message
     *
     * @param cryMessage the value for cost.cry_message
     *
     * @mbg.generated
     */
    public void setCryMessage(String cryMessage) {
        this.cryMessage = cryMessage == null ? null : cryMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.ct_date
     *
     * @return the value of cost.ct_date
     *
     * @mbg.generated
     */
    public Date getCtDate() {
        return ctDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.ct_date
     *
     * @param ctDate the value for cost.ct_date
     *
     * @mbg.generated
     */
    public void setCtDate(Date ctDate) {
        this.ctDate = ctDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost.uid
     *
     * @return the value of cost.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost.uid
     *
     * @param uid the value for cost.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}