package com.work.pojo;

import java.util.Date;

public class Income {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.wages
     *
     * @mbg.generated
     */
    private Double wages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.ws_message
     *
     * @mbg.generated
     */
    private String wsMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.gains
     *
     * @mbg.generated
     */
    private Double gains;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.gs_message
     *
     * @mbg.generated
     */
    private String gsMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.borrow
     *
     * @mbg.generated
     */
    private Double borrow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.bw_message
     *
     * @mbg.generated
     */
    private String bwMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.ie_repay
     *
     * @mbg.generated
     */
    private Double ieRepay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.iry_message
     *
     * @mbg.generated
     */
    private String iryMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.ie_date
     *
     * @mbg.generated
     */
    private Date ieDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column income.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.id
     *
     * @return the value of income.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.id
     *
     * @param id the value for income.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.wages
     *
     * @return the value of income.wages
     *
     * @mbg.generated
     */
    public Double getWages() {
        return wages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.wages
     *
     * @param wages the value for income.wages
     *
     * @mbg.generated
     */
    public void setWages(Double wages) {
        this.wages = wages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.ws_message
     *
     * @return the value of income.ws_message
     *
     * @mbg.generated
     */
    public String getWsMessage() {
        return wsMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.ws_message
     *
     * @param wsMessage the value for income.ws_message
     *
     * @mbg.generated
     */
    public void setWsMessage(String wsMessage) {
        this.wsMessage = wsMessage == null ? null : wsMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.gains
     *
     * @return the value of income.gains
     *
     * @mbg.generated
     */
    public Double getGains() {
        return gains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.gains
     *
     * @param gains the value for income.gains
     *
     * @mbg.generated
     */
    public void setGains(Double gains) {
        this.gains = gains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.gs_message
     *
     * @return the value of income.gs_message
     *
     * @mbg.generated
     */
    public String getGsMessage() {
        return gsMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.gs_message
     *
     * @param gsMessage the value for income.gs_message
     *
     * @mbg.generated
     */
    public void setGsMessage(String gsMessage) {
        this.gsMessage = gsMessage == null ? null : gsMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.borrow
     *
     * @return the value of income.borrow
     *
     * @mbg.generated
     */
    public Double getBorrow() {
        return borrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.borrow
     *
     * @param borrow the value for income.borrow
     *
     * @mbg.generated
     */
    public void setBorrow(Double borrow) {
        this.borrow = borrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.bw_message
     *
     * @return the value of income.bw_message
     *
     * @mbg.generated
     */
    public String getBwMessage() {
        return bwMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.bw_message
     *
     * @param bwMessage the value for income.bw_message
     *
     * @mbg.generated
     */
    public void setBwMessage(String bwMessage) {
        this.bwMessage = bwMessage == null ? null : bwMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.ie_repay
     *
     * @return the value of income.ie_repay
     *
     * @mbg.generated
     */
    public Double getIeRepay() {
        return ieRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.ie_repay
     *
     * @param ieRepay the value for income.ie_repay
     *
     * @mbg.generated
     */
    public void setIeRepay(Double ieRepay) {
        this.ieRepay = ieRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.iry_message
     *
     * @return the value of income.iry_message
     *
     * @mbg.generated
     */
    public String getIryMessage() {
        return iryMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.iry_message
     *
     * @param iryMessage the value for income.iry_message
     *
     * @mbg.generated
     */
    public void setIryMessage(String iryMessage) {
        this.iryMessage = iryMessage == null ? null : iryMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.ie_date
     *
     * @return the value of income.ie_date
     *
     * @mbg.generated
     */
    public Date getIeDate() {
        return ieDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.ie_date
     *
     * @param ieDate the value for income.ie_date
     *
     * @mbg.generated
     */
    public void setIeDate(Date ieDate) {
        this.ieDate = ieDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column income.uid
     *
     * @return the value of income.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column income.uid
     *
     * @param uid the value for income.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}